import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <label className="dropdown">
        <div className="dd-toggle">Menu</div>

        <input type="checkbox" className="dd-input" id="test" />

        <ul className="dd-menu">
          <li>Posts</li>
          <li>About</li>
          <li>Book Reviews</li>
          <li className="divider"></li>
          <li>
            <a href="#">Feed</a>
          </li>
        </ul>
      </label>
      <div className="window">
        <div className="title-bar">
          <h1 className="title">Hi, I'm Monty</h1>
        </div>
        <div className="separator"></div>

        <div className="window-pane">
          <h4 style={{ textAlign: "center" }}>
            Orci varius natoque penatibus et magnis dis parturient montes
          </h4>
        </div>
      </div>

      <div className="window">
        <div className="window-pane">
          <p style={{ lineHeight: "1.6" }}>
            In lacus enim, efficitur eu dictum ullamcorper, molestie eget urna.
            Proin at lectus quis dui tempus suscipit sit amet in ex.
            Pellentesque auctor et augue non feugiat. Aenean nisi risus, mollis
            eu augue quis, faucibus finibus purus. Mauris dapibus tortor
            efficitur est dictum, ac suscipit dolor scelerisque.
          </p>
        </div>
      </div>

      <div className="window">
        <div className="window-pane">
          <p style={{ lineHeight: "1.5" }}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
            ornare lorem id volutpat vehicula. Nunc pretium ornare orci lobortis
            consectetur. Fusce facilisis orci eu nulla vehicula, et aliquam odio
            mollis. Nunc condimentum nibh sed odio dictum hendrerit. Quisque
            commodo erat finibus odio aliquam rhoncus. Sed aliquet neque dui,
            nec iaculis arcu pulvinar eu. Cras quis lacus vel mi egestas
            malesuada non id felis.{" "}
          </p>
          <ul>
            <li>
              <strong>Testing</strong> - Aliquam placerat lacus fringilla
              commodo convallis. Quisque auctor est nec dolor semper, vitae
              cursus nisi rutrum. Cras rhoncus, sem eu feugiat pellentesque,
              nisl nisi consequat diam
            </li>
            <li>
              <strong>Testing</strong> - Vivamus pretium condimentum mauris, ac
              feugiat lectus facilisis eu. Ut facilisis libero nec tellus congue
              malesuada sed eget odio.
            </li>
            <li>
              <strong>Testing</strong> - Proin at lectus quis dui tempus
              suscipit sit amet in ex. Pellentesque auctor et augue non feugiat.
              Aenean nisi risus, mollis eu augue quis, faucibus finibus purus.
              Mauris dapibus tortor efficitur est dictum, ac suscipit dolor
              scelerisque. Morbi euismod erat sit amet nibh tempus convallis.
            </li>
            <li>
              <strong>Testing</strong> - Ut eu aliquet lacus. Ut maximus
              faucibus lacus in gravida. Orci varius natoque penatibus et magnis
              dis parturient montes, nascetur ridiculus mus. Nunc sagittis
              pharetra posuere.
            </li>
            <li>
              <strong>Testing</strong> - Suspendisse potenti. Pellentesque
              interdum leo leo, eget ultrices nisl maximus at. Pellentesque
              habitant morbi tristique senectus et netus et malesuada fames ac
              turpis egestas.
            </li>
          </ul>
        </div>
      </div>

      <div style={{ display: "flex" }}>
        <div className="window" style={{ width: "50%" }}>
          <div className="title-bar">
            <h1 className="title">Post</h1>
          </div>
          <div className="separator"></div>
          <div className="window-pane">
            <ul>
              <li>
                <a href="#">Typescript</a>
              </li>
              <li>
                <a href="#">R.I.P Localhost</a>
              </li>
              <li>
                <a href="#">Interview Questions</a>
              </li>
            </ul>
          </div>
        </div>
        <div className="window" style={{ width: "50%" }}>
          <div className="title-bar">
            <h1 className="title">Builds</h1>
          </div>
          <div className="separator"></div>
          <div className="window-pane">
            <ul>
              <li>
                <a href="#">WhatsApp</a>
              </li>
              <li>
                <a href="#">Hulu-Overview</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
